// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ScreenTemp_screen_init(void)
{
ui_ScreenTemp = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelScreen = lv_obj_create(ui_ScreenTemp);
lv_obj_set_width( ui_PanelScreen, lv_pct(100));
lv_obj_set_height( ui_PanelScreen, lv_pct(100));
lv_obj_set_align( ui_PanelScreen, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PanelScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelScreen, lv_color_hex(0x160693), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_PanelScreen, lv_color_hex(0x064E93), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_PanelScreen, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_PanelScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_PanelScreen, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(ui_PanelScreen, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelScreen, 0, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelScreen, 10, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_PanelTemp = lv_obj_create(ui_PanelScreen);
lv_obj_set_height( ui_PanelTemp, 60);
lv_obj_set_width( ui_PanelTemp, lv_pct(100));
lv_obj_set_x( ui_PanelTemp, lv_pct(0) );
lv_obj_set_y( ui_PanelTemp, lv_pct(-40) );
lv_obj_set_align( ui_PanelTemp, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelTemp,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelTemp, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_SPACE_BETWEEN);
lv_obj_clear_flag( ui_PanelTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelTemp, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelTemp, lv_color_hex(0x3B5A8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_PanelTemp, lv_color_hex(0x4032B2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_PanelTemp, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_PanelTemp, lv_color_hex(0x0B0546), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PanelTemp, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_PanelTemp, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_PanelTemp, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_PanelTemp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_PanelTemp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelInTemp = lv_obj_create(ui_PanelTemp);
lv_obj_set_width( ui_PanelInTemp, 100);
lv_obj_set_height( ui_PanelInTemp, 50);
lv_obj_set_align( ui_PanelInTemp, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelInTemp,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelInTemp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelInTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelInTemp, lv_color_hex(0x120561), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelInTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelInTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelInTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelInDesc = lv_label_create(ui_PanelInTemp);
lv_obj_set_width( ui_LabelInDesc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelInDesc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelInDesc, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelInDesc,"Innen");
lv_obj_set_style_text_color(ui_LabelInDesc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelInDesc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelInTemp = lv_label_create(ui_PanelInTemp);
lv_obj_set_width( ui_LabelInTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelInTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelInTemp, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LabelInTemp,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_LabelInTemp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_label_set_text(ui_LabelInTemp,"12,34 °C");
lv_obj_set_style_text_color(ui_LabelInTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelInTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelInTemp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelOutTemp = lv_obj_create(ui_PanelTemp);
lv_obj_set_width( ui_PanelOutTemp, 100);
lv_obj_set_height( ui_PanelOutTemp, 50);
lv_obj_set_align( ui_PanelOutTemp, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelOutTemp,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelOutTemp, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelOutTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelOutTemp, lv_color_hex(0x120561), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelOutTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelOutTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelOutTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelOuttemp = lv_label_create(ui_PanelOutTemp);
lv_obj_set_width( ui_LabelOuttemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOuttemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelOuttemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelOuttemp,"Aussen");
lv_obj_set_style_text_color(ui_LabelOuttemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOuttemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelOutTemp = lv_label_create(ui_PanelOutTemp);
lv_obj_set_width( ui_LabelOutTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelOutTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelOutTemp, lv_pct(25) );
lv_obj_set_y( ui_LabelOutTemp, lv_pct(-40) );
lv_obj_set_align( ui_LabelOutTemp, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_LabelOutTemp,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_LabelOutTemp, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_LabelOutTemp,"-12,34 °C");
lv_obj_set_style_text_color(ui_LabelOutTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelOutTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelOutTemp, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartTemp = lv_chart_create(ui_PanelScreen);
lv_obj_set_width( ui_ChartTemp, 244);
lv_obj_set_height( ui_ChartTemp, 124);
lv_obj_set_align( ui_ChartTemp, LV_ALIGN_CENTER );
lv_chart_set_type( ui_ChartTemp, LV_CHART_TYPE_LINE);
lv_chart_set_axis_tick( ui_ChartTemp, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_ChartTemp, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
lv_chart_set_axis_tick( ui_ChartTemp, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, false, 25);
lv_chart_series_t* ui_ChartTemp_series_1 = lv_chart_add_series(ui_ChartTemp, lv_color_hex(0x808080), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_ChartTemp_series_1_array[] = { 0,10,20,40,80,80,40,20,10,0 };
lv_chart_set_ext_y_array(ui_ChartTemp, ui_ChartTemp_series_1, ui_ChartTemp_series_1_array);
lv_obj_set_style_radius(ui_ChartTemp, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ChartTemp, lv_color_hex(0x026374), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ChartTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ChartTemp, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_line_color(ui_ChartTemp, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ChartTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_ChartTemp, lv_color_hex(0xD3D3FC), LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ChartTemp, 255, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_line_color(ui_ChartTemp, lv_color_hex(0x081473), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_line_opa(ui_ChartTemp, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ChartTemp, lv_color_hex(0x080233), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ChartTemp, 255, LV_PART_TICKS| LV_STATE_DEFAULT);

}
