// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenTemp
void ui_ScreenTemp_screen_init(void);
extern lv_obj_t *ui_ScreenTemp;
extern lv_obj_t *ui_PanelScreen;
extern lv_obj_t *ui_PanelTemp;
extern lv_obj_t *ui_PanelInTemp;
extern lv_obj_t *ui_LabelInDesc;
extern lv_obj_t *ui_LabelInTemp;
extern lv_obj_t *ui_PanelOutTemp;
extern lv_obj_t *ui_LabelOuttemp;
extern lv_obj_t *ui_LabelOutTemp;
extern lv_obj_t *ui_ChartTemp;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
